"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def wave_file_writer(filename, pcm, channels=..., rate=..., sample_width=...) -> None:
    ...

def parse_speech_config(markdown_content):
    """Parses the markdown content to extract speakers and voices, dynamically matching active speakers in the transcript."""
    ...

def get_gemini_api_keys():
    ...

def process_file(md_file, wav_file, previous_id, api_state):
    ...

def process_directory(directory) -> None:
    ...

def main() -> None:
    """Parse CLI arguments and generate TTS audio from prompt files in a directory.

    This is the entrypoint for the ``genai-tts`` console script installed by
    ``pyproject.toml``.  Equivalent to running
    ``python -m storybuilder.genai.client --dir <directory>``.
    """
    ...

if __name__ == "__main__":
    ...
