queue_rules:
  - name: checks-pass
    merge_conditions:
      - "#check-failure = 0"
      - check-success ~= ^run_tests / test-results$
    branch_protection_injection_mode: none
    queue_conditions:
      - base = main
merge_queue:
  status_comments: all
  queue_controls_comment: true
  skip_intermediate_results: false
  reset_on_external_merge: always
  max_parallel_checks: 3
scopes:
  source:
    files:
      tests:
        include:
          - tests/**/*
      source:
        include:
          - src/**/*
      scripts:
        include:
          - scripts/**/*
merge_protections_settings:
  auto_merge_conditions:
    - check-success ~= ^run_tests / test-results$
    - "#check-pending = 0"
    - "#deployment-failure = 0"
    - -conflict
    - "#check-timed-out = 0"
pull_request_rules:
  - name: Auto-merge approved PRs
    conditions:
      - base = main
      - "#approved-reviews-by >= 1"
      - "#changes-requested-reviews-by = 0"
      - "#check-failure = 0"
      - "#check-pending = 0"
      - "#deployment-failure = 0"
      - check-success ~= ^run_tests / test-results$
    actions:
      merge:
        method: squash
  - name: Fix conflicts
    conditions:
      - -draft
      - conflict
      - base = main
    actions:
      label:
        add:
          - "@jules"
      comment:
        message: "@jules can you fix the merge conflicts?"
  - name: Keep PRs up to date
    conditions:
      - -draft
      - "#commits-behind >= 1"
    actions:
      update: null
