# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python312:
      python.version: '3.12'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: python -m pip install uv
  displayName: 'Install uv'

- script: uv sync --all-extras --dev
  displayName: 'Install dependencies'

- script: uv run python -m spacy download en_core_web_sm
  displayName: 'Download spaCy en_core_web_sm model'

- script: uv run python -m spacy download en_core_web_lg
  displayName: 'Download spaCy en_core_web_lg model'

- script: uv run pytest
  displayName: 'pytest'
