# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python312:
      python.version: '3.12'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      python -m pip install uv
      uv sync --all-extras --dev
      uv run python -m spacy download en_core_web_sm
      uv run python -m spacy download en_core_web_lg
      uv run pytest
  displayName: 'Install dependencies and run pytest'
