[project]
name        = "storybuilder"
version     = "0.1.0"
description = "Add your description here"
readme      = "README.md"
#authors = [{name = "jgeofil", email = "jeremy.geo@gmail.com"}]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "braintrust>=0.25.0",
    "cartesia>=3.2.0",
    "chromadb>=1.5.9",
    "google-adk[a2a,all,db,eval]>=2.2.0",
    "google-cloud-aiplatform[adk,ag2,agent-engines]>=1.158.0",
    "google-cloud-storage>=3.12.0",
    "google-genai>=2.8.0",
    "ibm-watsonx-orchestrate>=2.11.0",
    "lsprotocol==2023.0.1",
    "matplotlib>=3.10.9",
    "openai>=2.41.0",
    "opentelemetry-distro>=0.63b1",
    "opentelemetry-exporter-otlp>=1.42.1",
    "pandas>=2.3.3",
    "plotly>=6.8.0",
    "pygls==1.0.0",
    "pysocks>=1.7.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=5.5.1",
    "spacy[cuda12x]>=3.8.14",
    "streamlit>=1.58.0",
    "tqdm>=4.68.1",
    "transformers>=5.10.2",
    "xai-sdk>=1.15.0",
    "opentelemetry-instrumentation-asyncio==0.63b1",
    "opentelemetry-instrumentation-dbapi==0.63b1",
    "opentelemetry-instrumentation-logging==0.63b1",
    "opentelemetry-instrumentation-sqlite3==0.63b1",
    "opentelemetry-instrumentation-threading==0.63b1",
    "opentelemetry-instrumentation-urllib==0.63b1",
    "opentelemetry-instrumentation-wsgi==0.63b1",
    "opentelemetry-instrumentation-openai-v2",
    "opentelemetry-instrumentation-vertexai>=2.0b0",
    "opentelemetry-instrumentation-aiohttp-client==0.63b1",
    "opentelemetry-instrumentation-aiohttp-server==0.63b1",
    "opentelemetry-instrumentation-click==0.63b1",
    "opentelemetry-instrumentation-fastapi==0.63b1",
    "opentelemetry-instrumentation-grpc==0.63b1",
    "opentelemetry-instrumentation-httpx==0.63b1",
    "opentelemetry-instrumentation-jinja2==0.63b1",
    "opentelemetry-instrumentation-redis==0.63b1",
    "opentelemetry-instrumentation-requests==0.63b1",
    "opentelemetry-instrumentation-sqlalchemy==0.63b1",
    "opentelemetry-instrumentation-starlette==0.63b1",
    "opentelemetry-instrumentation-tortoiseorm==0.63b1",
    "opentelemetry-instrumentation-urllib3==0.63b1",
]

[project.scripts]
downloader = "storybuilder.downloader.cli:main"
genai-tts  = "storybuilder.genai.tts:main"

[build-system]
requires      = ["uv_build>=0.11.15,<0.12.0"]
build-backend = "uv_build"

[tool.uv.extra-build-dependencies]
cupy = ["pkg_resources"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
]
