# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.inclusions=src/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage

sonar.global.exclusions=azure-pipelines.yml,**/azure-pipelines.yml,**/*.yml,**/*.yaml,**/*.sh,**/scripts/**,**/tests/**,**/doc/**,**/.github/**
sonar.exclusions=azure-pipelines.yml,**/azure-pipelines.yml,**/*.yml,**/*.yaml,**/*.sh,**/scripts/**,**/tests/**,**/doc/**,**/.github/**
sonar.iac.exclusions=azure-pipelines.yml,**/azure-pipelines.yml,**/*.yml,**/*.yaml

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=*
sonar.issue.ignore.multicriteria.e1.resourceKey=azure-pipelines.yml
sonar.issue.ignore.multicriteria.e2.ruleKey=*
sonar.issue.ignore.multicriteria.e2.resourceKey=**/azure-pipelines.yml
