"""
This type stub file was generated by pyright.
"""

PROMPTS_DIR = ...
STORIES_DIR = ...
def get_prompt(name: str) -> str:
    """Reads a prompt from the prompts/ directory."""
    ...

def get_story(name: str) -> str:
    """Reads a story from the stories/ directory."""
    ...

