"""
This type stub file was generated by pyright.
"""

import sys

"""Tools for the TTS Prompt Crafter ADK agent.

Provides file I/O and prompt splitting as callable functions
that ADK can expose to the LLM as tools.
"""
_PROJECT_ROOT = ...
_STORIES_DIR = ...
_SPLIT_SCRIPT_DIR = ...
if _SPLIT_SCRIPT_DIR not in sys.path:
    ...
def read_story(story_path: str) -> str:
    """Read a story from disk by absolute path or story name.

    Args:
        story_path: The absolute path to the story markdown file or a
            story name that exists under ``stories/text``.

    Returns:
        The full text content of the story file.
    """
    ...

def list_stories(directory: str | None = ...) -> str:
    """List available story markdown files in a directory.

    Args:
        directory: The absolute path to the directory containing story files.
            If omitted, defaults to ``stories/text``.

    Returns:
        A newline-separated list of story file paths found in the directory.
    """
    ...

def write_scene_file(story_path: str, filename: str, content: str) -> str:
    """Write a TTS scene prompt file to the resolved output directory.

    The first argument can be either a story path or an existing output
    directory. When a story path is provided, the output directory is created
    as a sibling ``output`` subdirectory next to the story file.

    Args:
        story_path: The absolute path to the original story file or an
            output directory path.
        filename: The scene filename to create (e.g. '01-scene1.md').
            Must match the glob pattern '*-scene*.md'.
        content: The full markdown content of the scene prompt file.

    Returns:
        A confirmation message with the path of the written file.
    """
    ...

def split_scene_files(story_path: str) -> str:
    """Split TTS scene prompt files to respect the 2-voice limit.

    Runs the split_prompts processor on the resolved output directory.
    This chunks scene files by speaker count (max 2) and character length
    (max 1800), producing sequentially numbered '*-part.md' files.

    Args:
        story_path: The absolute path to the original story file or an
            existing output directory path.

    Returns:
        A status message listing the resulting part files.
    """
    ...

