import os
import shutil
import tempfile
import unittest


class TestReadStory(unittest.TestCase):
    def setUp(self) -> None: ...

    def tearDown(self) -> None: ...

    def test_read_existing_story(self) -> None: ...

    def test_read_nonexistent_story(self) -> None: ...

    def test_read_relative_path_rejected(self) -> None: ...

    def test_read_story_by_name(self) -> None: ...


class TestListStories(unittest.TestCase):
    def setUp(self) -> None: ...

    def tearDown(self) -> None: ...

    def test_list_md_files(self) -> None: ...

    def test_list_empty_directory(self) -> None: ...

    def test_list_nonexistent_directory(self) -> None: ...

    def test_list_relative_path_rejected(self) -> None: ...

    def test_list_default_directory(self) -> None: ...


class TestWriteSceneFile(unittest.TestCase):
    def setUp(self) -> None: ...

    def tearDown(self) -> None: ...

    def test_write_creates_output_dir_and_file(self) -> None: ...

    def test_write_rejects_invalid_filename(self) -> None: ...

    def test_write_rejects_non_md_filename(self) -> None: ...

    def test_write_rejects_relative_path(self) -> None: ...

    def test_write_accepts_output_directory(self) -> None: ...


class TestSplitSceneFiles(unittest.TestCase):
    def setUp(self) -> None: ...

    def tearDown(self) -> None: ...

    def test_split_produces_parts(self) -> None: ...

    def test_split_no_output_dir(self) -> None: ...

    def test_split_no_scene_files(self) -> None: ...

    def test_split_rejects_relative_path(self) -> None: ...

    def test_split_accepts_output_directory(self) -> None: ...
