version: 2.1

jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Install dependencies
          command: uv sync --all-extras --dev
      - run:
          name: Install CircleCI CLI
          command: |
            export DEBIAN_FRONTEND=noninteractive
            curl -1sLf 'https://packages.circleci.com/public/setup.deb.sh' | sudo -E bash
            sudo apt-get install -y circleci
            circleci extension install testsuite
      - run:
          name: Run tests
          command: circleci testsuite run "ci tests"
      - store_test_results:
          path: test-reports
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
