version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: python/default
      tag: "3.12"
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Install dependencies
          command: uv sync --all-extras --dev
      - run:
          name: Install CircleCI CLI
          command: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/main/install.sh | sudo bash
      - run:
          name: Run tests
          command: circleci testsuite run "ci tests"
      - store_test_results:
          path: test-reports
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
