import unittest
from storybuilder.genai.client import (
    _build_speech_config,
    _extract_active_speakers,
    _parse_voice_mappings,
)


class TestParseSpeechConfigSplit(unittest.TestCase):
    def test_parse_voice_mappings(self) -> None: ...

    def test_extract_active_speakers(self) -> None: ...

    def test_build_speech_config(self) -> None: ...

    def test_build_speech_config_fallback_active(self) -> None: ...

    def test_build_speech_config_fallback_preamble(self) -> None: ...

    def test_build_speech_config_single(self) -> None: ...

    def test_build_speech_config_empty(self) -> None: ...
