from _typeshed import Incomplete

import unittest
from unittest.mock import patch
import pytest
from storybuilder.genai.client import main as client_main
from storybuilder.genai.client import parse_speech_config
from storybuilder.genai.tts import main as tts_main


class TestGenAIClient(unittest.TestCase):
    def test_parse_speech_config_multi_speaker(self) -> None: ...

    def test_parse_speech_config_single_speaker(self) -> None: ...

    def test_parse_speech_config_no_speakers(self) -> None: ...

    def test_parse_speech_config_max_two_voices(self) -> None: ...

    def test_parse_speech_config_active_speakers(self) -> None: ...

    def test_parse_speech_config_active_speaker_no_voice_fallback(self) -> None: ...

    def test_parse_speech_config_active_speaker_padded(self) -> None: ...

    def test_extract_markdown_block(self) -> None: ...

    def test_tts_entrypoint_resolves_to_client_main(self) -> None: ...

    def test_main_processes_existing_directory(self) -> None: ...

    def test_main_exits_nonzero_for_missing_directory(self) -> None: ...

    def test_get_gemini_api_keys_primary_only(self) -> None: ...

    def test_get_gemini_api_keys_with_rotations(self) -> None: ...

    def test_apikey_rotator(self) -> None: ...

    def test_handle_exception_404(self) -> None: ...

    @patch("time.sleep")
    def test_handle_exception_quota_rotation(self, mock_sleep: Incomplete) -> None: ...
