"""
This type stub file was generated by pyright.
"""

print_lock = ...
cache_lock = ...
metadata_cache = ...
def safe_print(*args, **kwargs): # -> None:
    """
    Thread-safe print to avoid interleaved output.
    """
    ...

def load_cache(cache_dir): # -> None:
    """
    Loads the metadata cache from cache_dir/metadata_cache.json.
    """
    ...

def save_cache(cache_dir): # -> None:
    """
    Saves the metadata cache to cache_dir/metadata_cache.json.
    """
    ...

