"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
if __name__ == "__main__" and __package__ is None:
    ...
def main():
    ...

if __name__ == "__main__":
    ...
