"""
This type stub file was generated by pyright.
"""

def parse_nifty_date(date_str, reference_date=...): # -> _Date | None:
    """
    Parses Nifty date strings which can be in two formats:
    - Standard Unix ls older file format: 'Dec  4  2025' -> MMM DD YYYY
    - Standard Unix ls recent file format: 'Jun  6 08:55' or 'May 12 19:52' -> MMM DD HH:MM (no year)

    If the year is missing, it is inferred based on the reference_date (defaulting to today).
    If the inferred date would be in the future relative to the reference_date, it is
    assumed to be from the previous year.
    """
    ...

