"""
This type stub file was generated by pyright.
"""

BASE_URL = ...
PROXIES = ...
ENABLE_ROTATION: bool = ...
def safe_print(*args, **kwargs): # -> None:
    ...

def rotate_windscribe_ip(): # -> bool:
    """
    Rotates the IP address using windscribe-cli.
    """
    ...

def fetch_page(url, delay, headers=..., max_retries=...): # -> Response | None:
    """
    Fetches a URL with retries and custom headers.
    Optionally routes through global proxies and triggers Windscribe IP rotation on refusal.
    """
    ...

