"""
This type stub file was generated by pyright.
"""

seen_folders = ...
seen_folders_lock = ...
def get_subcategories(category, delay): # -> list[Any]:
    """
    Scrapes the category index page to find all subcategory folders.
    Returns a list of dicts: [{'name': 'Adult Friends', 'url': 'https://nifty.org/nifty/gay/adult-friends/'}]
    """
    ...

def parse_listing_rows(soup): # -> list[Any]:
    """
    Parses listing rows from Nifty index pages.
    Handles both new 'div.ftr' style rows and old 'tr' style table rows.
    Returns a list of dicts: [{'size': '13K', 'date_str': 'Jun 6 08:55', 'name': 'title', 'href': 'url'}]
    """
    ...

def scrape_subcategory(sub_url, start_date, end_date, delay, force_scan=...): # -> list[Any]:
    """
    Crawls a subcategory directory, handling pagination.
    Uses the local metadata cache to avoid crawling previously scraped pages.
    Returns all stories/directories in this subcategory that fall in the date range.
    """
    ...

def scrape_multi_chapter_folder(folder_url, folder_date, start_date, end_date, delay, force_scan=...): # -> list[Any]:
    """
    Crawls a multi-chapter folder (represented by a 'Dir' entry).
    Uses caching based on folder_date to avoid fetching unless the folder changed.
    If at least one chapter falls within the date range [start_date, end_date],
    returns all chapters from this folder. Otherwise, returns an empty list.
    """
    ...

def process_subcategory(sub, start_date, end_date, args): # -> list[Any]:
    """
    Crawls a single subcategory and all its multi-chapter folders,
    collecting metadata to prepare story targets for downloading.
    """
    ...

