"""
This type stub file was generated by pyright.
"""

def upload_many(bucket_name: str, filenames: list[str], source_directory: str = ..., workers: int = ...) -> None:
    ...

def upload_many_gcs(bucket_name: str, prefix: str, filenames: list[str], source_directory: str = ..., workers: int = ...) -> None:
    """Upload files to GCS using transfer_manager with an optional object prefix.

    Returns immediately when filenames is empty.
    """
    ...

def upload_many_s3(bucket_name: str, prefix: str, filenames: list[str], source_directory: str = ..., workers: int = ...) -> None:
    """Upload files to S3 with keys rooted at the optional prefix.

    Returns immediately when filenames is empty. Requires boto3 at runtime.
    """
    ...

if __name__ == "__main__":
    directory = ...
    files_to_upload = ...
