"""
This type stub file was generated by pyright.
"""

def save_story(story_url, output_path, story_date, delay): # -> bool:
    """
    Downloads the story from story_url and saves it to output_path.
    If the response is HTML, extracts plain text from body paragraphs.
    Prepends basic metadata (Title, Author, Date, URL) to the saved file.
    """
    ...

def download_single_target(idx_str, url, output_paths, story_date, delay, force=...): # -> bool:
    """
    Downloads a single target story and handles duplicate copy replication.
    Returns True if successful, False otherwise.
    """
    ...

