"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Optional

_env_loaded = ...
def load_env(dotenv_path: Optional[Path] = ...) -> None:
    """
    Load environment variables from .env file.
    Called once at startup; subsequent calls are no-ops.

    Args:
        dotenv_path: Optional path to .env file. Defaults to project root.
    """
    ...

def get_api_key(name: str, required: bool = ...) -> Optional[str]:
    """
    Get an API key from environment variables.

    Args:
        name: Environment variable name (e.g., "GEMINI_API_KEY", "CARTESIA_API_KEY")
        required: If True, raises ValueError when key is missing or empty.

    Returns:
        The API key value, or None if not required.

    Raises:
        ValueError: If required=True and key is missing or empty.
    """
    ...

def get_optional_api_key(name: str) -> Optional[str]:
    """Get an optional API key that may be missing."""
    ...

def get_stable_api_key(base_name: str) -> Optional[str]:
    """
    Get a single API key WITHOUT rotation (for TTS use cases).

    TTS requires consistent voice across multiple API calls within a story.
    Using rotation breaks the chain and causes voice mismatch.

    Args:
        base_name: Base environment variable name (e.g., "GEMINI_API_KEY")

    Returns:
        The API key value, or None if not set.
    """
    ...

def get_api_keys_with_rotation(base_name: str) -> list[tuple[str, str]]:
    """
    Get multiple API keys with numeric suffix rotation (e.g., GEMINI_API_KEY_1, GEMINI_API_KEY_2).

    Use for non-TTS operations where quota rotation is acceptable.
    For TTS generation, use a single key to maintain consistency across calls.

    Args:
        base_name: Base environment variable name (e.g., "GEMINI_API_KEY")

    Returns:
        List of (env_var_name, key_value) tuples, starting with the base key.
    """
    ...

