"""
This type stub file was generated by pyright.
"""

import logging
from pathlib import Path
from typing import Optional

DEFAULT_FORMAT = ...
SIMPLE_FORMAT = ...
_configured = ...
def configure_logging(level: int = ..., log_file: Optional[Path] = ..., format_string: str = ..., force: bool = ...) -> None:
    """
    Configure logging for the application.

    Called once at startup; subsequent calls are no-ops unless force=True.

    Args:
        level: Logging level (default: INFO)
        log_file: Optional file path to write logs to
        format_string: Log format string
        force: Force reconfiguration even if already configured
    """
    ...

def get_logger(name: str, level: Optional[int] = ...) -> logging.Logger:
    """
    Get a logger with the given name.

    Args:
        name: Logger name (typically __name__)
        level: Optional level override for this logger

    Returns:
        Configured logger instance
    """
    ...

def set_library_log_levels(levels: Optional[dict[str, int]] = ...) -> None:
    """
    Set log levels for noisy third-party libraries.

    Args:
        levels: Dict of logger name -> level. Defaults to common noisy libraries.
    """
    ...

