import sys
import unittest
from pathlib import Path
from storybuilder.dashboard.data import StorySearchQuery


class TestStorySearchQueryDefaults(unittest.TestCase):
    def test_default_fts_query(self) -> None: ...

    def test_default_category(self) -> None: ...

    def test_default_author(self) -> None: ...

    def test_default_year_range(self) -> None: ...

    def test_default_entity_text(self) -> None: ...

    def test_default_entity_label(self) -> None: ...

    def test_default_limit(self) -> None: ...


class TestStorySearchQueryCustom(unittest.TestCase):
    def test_custom_fts_query(self) -> None: ...

    def test_custom_category(self) -> None: ...

    def test_custom_author(self) -> None: ...

    def test_custom_year_range(self) -> None: ...

    def test_custom_entity_text(self) -> None: ...

    def test_custom_entity_label(self) -> None: ...

    def test_custom_limit(self) -> None: ...

    def test_all_custom_fields(self) -> None: ...
