# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Dependabot auto-label
on: pull_request

permissions:
  pull-requests: write
  issues: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Add a label for all production dependencies
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: gh pr edit "$PR_URL" --add-label "production"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
      - name: Find or Create Linear Issue and Prefix PR
        # You may pin to the exact commit or the version.
        # uses: ctriolo/action-find-or-create-linear-issue@77a2fd8d3b1bedc97fe8c91144b421baba91f4c2
        uses: ctriolo/action-find-or-create-linear-issue@v0.60
        with:
          # Linear API key generated from https://linear.app/settings/api
          linear-api-key: ${{secrets.LINEAR_API_KEY}}
          # Team key (e.g. ENG) for the Linear issue to create.
          linear-team-key: PRO
          # Team state ID for the created Linear issue.
          #linear-created-issue-state-id: # optional
          # Title prefix for the created Linear issue.
          linear-created-issue-title-prefix: GIT-
          # Comma deliminated label ids
          #linear-issue-label-ids: # optional
          # GitHub token required to modify the PR title.
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
