name: Pylint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: [ubuntu-latest, alirun]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
        
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev --prerelease=allow

      - name: Run pylint
        run: uv run pylint --errors-only src/

      - name: Lint code with Ruff
        run: uv run ruff check --fix --output-format=github
        continue-on-error: true
        
      - name: Check code formatting with Ruff
        run: uv run ruff format --diff
        continue-on-error: true

